// Column-based auto-layout algorithm for flows generated by the NLP assistant

import type { FlowNode } from "../types/flow";

interface LayoutConfig {
  columnGap: number;   // horizontal gap between columns (default 280)
  rowGap: number;      // vertical gap between nodes in same column (default 120)
  startX: number;      // x offset for first column (default 100)
  startY: number;      // y offset (default 100)
}

const DEFAULT_LAYOUT: LayoutConfig = {
  columnGap: 280,
  rowGap: 120,
  startX: 100,
  startY: 100,
};

// Column order for node types (left-to-right)
const COLUMN_ORDER: Record<string, number> = {
  trigger: 0,
  source: 1,
  filter: 2,
  executor: 3,
  sink: 4,
};

/**
 * Assign positions to nodes based on their type.
 * Nodes of the same type are stacked vertically.
 * Types are arranged left-to-right: trigger → source → filter → executor → sink
 */
export function layoutNodes(
  nodes: FlowNode[],
  config?: Partial<LayoutConfig>,
): FlowNode[] {
  const cfg = { ...DEFAULT_LAYOUT, ...config };

  // Group nodes by type
  const groups = new Map<string, FlowNode[]>();
  for (const node of nodes) {
    const group = groups.get(node.node_type) ?? [];
    group.push(node);
    groups.set(node.node_type, group);
  }

  const result: FlowNode[] = [];

  for (const [nodeType, typeNodes] of groups) {
    const col = COLUMN_ORDER[nodeType] ?? 3;
    const x = cfg.startX + col * cfg.columnGap;

    // Center the group vertically
    const totalHeight = (typeNodes.length - 1) * cfg.rowGap;
    const startYOffset = cfg.startY - totalHeight / 2;

    for (let i = 0; i < typeNodes.length; i++) {
      result.push({
        ...typeNodes[i],
        position: { x, y: startYOffset + i * cfg.rowGap },
      });
    }
  }

  return result;
}

/**
 * Generate edges for a standard pipeline layout.
 * Wires: each trigger → each source, each source → each executor, each executor → each sink.
 * If filters exist: source → filter → executor instead of source → executor.
 */
export function generatePipelineEdges(
  nodes: FlowNode[],
): Array<{ id: string; source: string; target: string }> {
  const byType = (t: string) => nodes.filter((n) => n.node_type === t);

  const triggers = byType("trigger");
  const sources = byType("source");
  const filters = byType("filter");
  const executors = byType("executor");
  const sinks = byType("sink");

  const edges: Array<{ id: string; source: string; target: string }> = [];
  let edgeIdx = 0;

  const wire = (from: FlowNode[], to: FlowNode[]) => {
    for (const s of from) {
      for (const t of to) {
        edges.push({
          id: `e${edgeIdx++}`,
          source: s.id,
          target: t.id,
        });
      }
    }
  };

  // trigger → source
  wire(triggers, sources);

  if (filters.length > 0) {
    // source → filter → executor
    wire(sources, filters);
    wire(filters, executors);
  } else {
    // source → executor
    wire(sources, executors);
  }

  // executor → sink
  wire(executors, sinks);

  return edges;
}
